[ERROR]	2025-07-21T10:55:53.344Z	a3d0fc61-cc77-43cb-b659-3a1e800f081d	Error
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 52, in lambda_handler
    rec = event["Records"][0]
          ~~~~~^^^^^^^^^^^
KeyError: 'Records'
