[ERROR]	2025-07-18T15:09:01.004Z	cb1abf11-641d-45f0-883f-58f04f9141d5	Error processing record: seek
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 94, in lambda_handler
    text = pdf_to_text(bucket, key)
  File "/var/task/lambda_function.py", line 56, in pdf_to_text
    reader = PyPDF2.PdfReader(obj["Body"])
  File "/opt/python/lib/python3.13/site-packages/PyPDF2/_reader.py", line 319, in __init__
    self.read(stream)
    ~~~~~~~~~^^^^^^^^
  File "/opt/python/lib/python3.13/site-packages/PyPDF2/_reader.py", line 1414, in read
    self._basic_validation(stream)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/python/lib/python3.13/site-packages/PyPDF2/_reader.py", line 1453, in _basic_validation
    stream.seek(0, os.SEEK_END)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
io.UnsupportedOperation: seek
