[ERROR] KeyError: 'actionGroup'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 129, in lambda_handler
    "actionGroup":   event["actionGroup"],
