[ERROR] KeyError: 'message'
Traceback (most recent call last):
  File "/var/task/dummy_lambda.py", line 107, in lambda_handler
    'message': result['message'],
